version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: güçlü_bir_parola
      MYSQL_DATABASE: aw_person        # İlk DB'yi oluşturur
    ports:
      - "3306:3306"
    volumes:
      - mysql_verileri:/var/lib/mysql
      - ./data:/docker-entrypoint-initdb.d   # SQL'lerin doğru klasörü
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 70s
      retries: 20

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      PMA_HOST: mysql
    ports:
      - "8080:80"

volumes:
  mysql_verileri:
